### ISSUE TITLE
What is the roadmap and vision?

### ISSUE THREAD

**Issue by datnamer** [blaze/libndtypes#4]
For dynd, this library and the blaze ecosystem?  I'm a bit confused by the separation of concerns of all these different libraries (blaze, datashape, dask, numba, this one etc). How will they eventualy fit together and what are the target goals?

Thanks.

**Comment by kwmsmith** [comment]
@datnamer Good questions, all.  This new project is just underway as of a few days ago, and its concrete vision, scope, and responsibility in relation to the other projects you name is a matter of active discussion.  It's been in @teoliphant's vision for a while now.  As you can see from the codebase, it's based off of DyND's type system.

We will have an 0.1 release in the near term, and around that time will provide documentation to help explain the project; going into the motivation here at this time would be premature.

**Comment by datnamer** [comment]
Thanks!

**Comment by datnamer** [comment]
This question was prompted by the 0.1 roadmap issue, but I didn't want to clutter it. Perhaps plans are materialized enough to include the answers. If not, feel free to ignore. 

Are there plans to be able to implement new stack allocated primitive or composite  immutable types? 

For the latter-  or are all the primitives from C++?

What about type vars and generics?

This is on my wishlist for simulations, but not sure if it something that would go more in numba.

**Comment by kwmsmith** [comment]
> Are there plans to be able to implement new stack allocated primitive or composite immutable types?

Just so I'm sure we're talking about the same things, please go into these terms in more detail, or provide pointers.

**Comment by datnamer** [comment]
Primitive type- A type consisting of contiguous  bits laid out in memory ex int64. Does not need to be boxed or allocated on the heap.

Composite immutable type- A struct/type with different immutable field- ie 'Immutable point (x,y)' Can be stack allocated and packed into an array. 

Generic type - Type(x,y) x <-Any float, y<- Any Int

**Comment by teoliphant** [comment]
Last year it became clear to me what the future of array-oriented computing should be.   The foundations of NumPy are:  dtypes, ufuncs, the numpy array, and a bunch of functions.

We would be better off is these foundations were more separated into individual libraries.   This perspective has been driving Continuum-sponsored development on Dynd for a year and led to the separation of the ndt library in dynd.  We lacked a separate python binding to it.   With Dynd developers moving on to other opportunities and without a simple focus on the datashape parsing concept, the separate python binding did not happen.   

Datashape is an extensible spec that can describe all kinds of data useful for analysis.    We need also a reference "parsing" library with a Python binding so that the spec can be "understood" by a program.   Eventually, there should be client libraries for this spec in Scala, R, Ruby, Node, etc.    A C/C++ reference library with a Python binding that can parse and define the data-shape spec is the goal of libndtypes.  

Ideally Pandas 2.0, xarray, numba, and even NumPy and Python some-day could use this type system (i.e. to replace the buffer-protocol "struct-string" syntax used to specify data). 

As soon as we get 0.2 out of libndtypes, we will have the numba team start to look at using it to build generic ufuncs and kernels over extensible types.  Those are the next steps for this effort. 

Dask is quite different and is a parallel framework that could someday use these tools, but for now has plenty to do just using NumPy and Pandas.  

Blaze is a very high-level query-optimization interface (SQL for Advanced Analytics).   Blaze is about transforming high-level NumPy-like and Pandas-like expressions on data-handles to back-ends (Dask, Spark, Impala, Hive, SQL, ...) to get a result.   

They are all part of the same story which is emerging and adapting as the technology advances in other areas as well . 

Thanks for the interest.   Drop me a line if you'd like to discuss further how these ideas could (or could not currently) help you with your next project.

**Comment by datnamer** [comment]
Hi Travis, 

Thanks very much for your thoughts. 

> over extensible types

Is the part I am specifically interested in. Currently the Numba JIT class is quite limited compared to what I would need to program the above sort of structures. (No operator overloading, generic classes, multimethods, stack allocated types etc).

Are there plans for these sort of advancements in the type system (or dtype system), or is this beyond the scope of Dynd, more for numba 3.0 etc...

As a more curiosity  bonus, how do you see this interoperating with untyped python code (classes and methods) 

This is more a informational request than a feature request as I think my needs are quite niche and I do not like to make feature requests of generously funded open source projects.

**Comment by teoliphant** [comment]
The numba efforts with libndtypes will need to be discussed with the Numba group and on the numba repository.    I hope the numba jit class can be used with libndtypes but libndtypes itself will not be about "computation" but simply description (the description might include a reference to a transformation that would have to be implemented later).   

Computation would be left to other libraries and projects.  Numba should be able to use JIT classes to provide the ability to define operations on types whose layout in memory and on disk is well described by libndtypes.     

A project using Numba and libndtypes could then define some or all of the things you mention.

**Comment by datnamer** [comment]
@seibert @sklam should I open  new issues for these things or is this too speculative right now?
